CREATE OR REPLACE VIEW XXBCM_RDER_SUMMARY
	 AS 
     SELECT TO_NUMBER(SUBSTR(ORDER_REF,3))  ORDER_REFERENCE,
 TO_CHAR(ORDER_DATE, 'MON-YY') ORDER_DATE,
 INITCAP(SUPPLIER_NAME) SUPPLIER_NAME,
 TO_CHAR(TOTAL_AMT,'99G999G990D99') TOTAL_AMT,
 ORDER_STATUS,
 INVOICE_REF,
  TO_CHAR(INVOICE_AMT,'99G999G990D99')INVOICE_AMT,
INVOICE_STATUS,
  CASE
    WHEN INVOICE_STATUS ='Paid' THEN 'OK'
    WHEN INVOICE_STATUS ='Pending' THEN 'To follow up'
   WHEN INVOICE_STATUS is null  THEN 'To Verify'
   
   END AS ACTION
    FROM (
    SELECT
    ORDER_REF,
    ORDER_DATE,
    SUPPLIER_NAME,
    SUM(TOTAL_AMT) TOTAL_AMT,
    ORDER_STATUS,
    INVOICE_REF,
    SUM(INVOICE_AMOUNT) INVOICE_AMT,
    INVOICE_STATUS
    FROM XXBCM_TRANSACTION
    WHERE INSTR(ORDER_REF, '-') = 0
    GROUP BY
    ORDER_REF,
    ORDER_DATE,
    SUPPLIER_NAME,
    ORDER_STATUS,
    INVOICE_REF,
    INVOICE_STATUS
    UNION ALL
    SELECT
    SUBSTR(ORDER_REF, 1,INSTR(ORDER_REF, '-', -1)-1) ORDER_REF,
    ORDER_DATE,
    SUPPLIER_NAME,
    SUM(TOTAL_AMT) TOTAL_AMT,
    ORDER_STATUS,
    INVOICE_REF,
    SUM(INVOICE_AMOUNT) INVOICE_AMT,
    INVOICE_STATUS
    FROM XXBCM_TRANSACTION
    WHERE INSTR(ORDER_REF, '-') > 0
    GROUP BY
    SUBSTR(ORDER_REF, 1,INSTR(ORDER_REF, '-', -1)-1),
    ORDER_DATE,
    SUPPLIER_NAME,
    ORDER_STATUS,
    INVOICE_REF,
    INVOICE_STATUS)
    WHERE TOTAL_AMT !=0
    ORDER BY ORDER_REF, TOTAL_AMT DESC, INVOICE_REF DESC ;
    
    COMMIT;
       

CREATE OR REPLACE VIEW XXBCM_THIRD_HIGHEST
	 AS
	 SELECT
	ORDER_REF,
	ORDER_DATE,
	SUPPLIER_NAME,
	TOTAL_AMT,
	ORDER_STATUS,
	(SELECT  listagg(INVOICE_REF, ', ') within GROUP (ORDER BY INVOICE_REF) AS INVOICE_REFS
	 FROM (SELECT DISTINCT  INVOICE_REF
			FROM XXBCM_TRANSACTION
			WHERE ORDER_REF LIKE (SELECT ORDER_REF || '%'
									FROM (SELECT TR2.*, ROWNUM rnum FROM
																	(SELECT * FROM XXBCM_TRANSACTION ORDER BY TOTAL_AMT DESC) TR2
																	WHERE ROWNUM <= 3 )
									WHERE rnum >= 3)
			AND INVOICE_REF IS NOT NULL
	ORDER BY INVOICE_REF)) INVOICES
	FROM (SELECT TR2.*, ROWNUM rnum FROM
									(SELECT * FROM XXBCM_TRANSACTION ORDER BY TOTAL_AMT DESC) TR2
									WHERE ROWNUM <= 3 )
                                    
   WHERE rnum >= 3;
   
   COMMIT;
   
   	CREATE OR REPLACE VIEW XXBCM_SUPPLIER_LIST
    AS
	SELECT (S.FIRST_NAME || ' ' || S.LAST_NAME) CONTACT_NAME,
    SUBSTR(S.TELEPHONE_NUMBER, 1, 3) || '-' || SUBSTR(S.TELEPHONE_NUMBER, 4) TELEPHONE_NUMBER,
    SUBSTR(S.MOBILE_NUMBER, 1, 4) || '-' || SUBSTR(S.MOBILE_NUMBER,4 ) MOBILE_NUMBER,
    COUNT(T.ORDER_REF) ORDERS,
     TO_CHAR(SUM(T.TOTAL_AMT),'99G999G990D99' )TOTAL_AMT
	FROM XXBCM_SUPPLIER S ,  XXBCM_TRANSACTION T 
	WHERE S.SUPPLIER_NAME = T.SUPPLIER_NAME
	AND T.ORDER_DATE BETWEEN TO_DATE('01/01/2017', 'DD/MM/YYYY') AND TO_DATE('31/08/2017', 'DD/MM/YYYY')
    GROUP BY (S.FIRST_NAME || ' ' || S.LAST_NAME),
    S.TELEPHONE_NUMBER,
    S.MOBILE_NUMBER;
    COMMIT;